export const PUMPS_FETCH_SUCCESS = 'PUMPS_FETCH_SUCCESS';
export const PUMPS_FETCH_FAILURE = 'PUMPS_FETCH_FAILURE';
export const SORT_HANDLER = 'SORT_HANDLER';
export const SELECTED_PUMP = 'SELECTED_PUMP';
export const FILTER_PUMP = 'FILTER_PUMP'